version: '3.9'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
    depends_on:
      - control-center
      - redis
      - mongodb

  control-center:
    build:
      context: ./control-center
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - mongodb
      - rag-system

  rag-system:
    build:
      context: ./internal-modules/rag-system
    ports:
      - '6333:6333'
    environment:
      - NODE_ENV=development
    volumes:
      - ./data:/app/data

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:5
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
