version: '3.8'

services:
  # API Server
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CONFIG_MODE=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=superior_rag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ../:/app
    depends_on:
      - postgres
      - qdrant
      - neo4j
      - redis
    networks:
      - superior-rag-network

  # PostgreSQL database
  postgres:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=superior_rag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../scripts/init_database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - superior-rag-network

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - superior-rag-network
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

  # Neo4j graph database
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j-data:/data
    networks:
      - superior-rag-network

  # Redis cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - superior-rag-network

networks:
  superior-rag-network:
    driver: bridge

volumes:
  postgres-data:
  qdrant-data:
  neo4j-data:
  redis-data:
