version: '3.8'

services:
  nexus-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose Nginx on 8080 host, container port 80
    depends_on:
      - nexus-server
    networks:
      - nexus-network
    restart: unless-stopped

  nexus-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      # Mount volumes relative to the docker-compose.yml location
      - ./server/uploads:/app/uploads
      - ./server/data:/app/data
      - ./server/logs:/app/logs
      - ./server/memory:/app/memory # Added memory volume
    environment:
      - NODE_ENV=production
      - PORT=3001
      - LLM_PROVIDER=${LLM_PROVIDER:-mock}
      - LLM_API_KEY=${LLM_API_KEY:-}
      - OLLAMA_BASE_URL=http://ollama:11434
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - OPENWEBUI_BASE_URL=${OPENWEBUI_BASE_URL:-http://openwebui:8000}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-turbo}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-3-haiku-20240307}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-openai/gpt-4-turbo}
      - GROQ_MODEL=${GROQ_MODEL:-llama3-70b-8192}
      - OPENWEBUI_MODEL=${OPENWEBUI_MODEL:-default}
    networks:
      - nexus-network
    restart: unless-stopped

  # Ollama service for local LLM hosting
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - nexus-network
    restart: unless-stopped

  # Open Web UI service (optional)
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_OPENAI_API=true
    ports:
      - "8000:8000"
    volumes:
      - openwebui-data:/app/backend/data
    networks:
      - nexus-network
    restart: unless-stopped

networks:
  nexus-network:
    driver: bridge

volumes:
  ollama-data:
  openwebui-data:
